# Docker Compose
version: "3.3"

# Define services
services:
  # Backend service
  ams_rest:
    build: ./ams_back
    ports:
      - "6066:8080"
    container_name: mce_ams_back2024
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/amsfullstack2024?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: akram
      SPRING_DATASOURCE_PASSWORD: akram@12ere
    networks:
      - ams_app2024

  # Frontend Service
  ams_front:
    build: ./ams_front
    container_name: mce_ams_front2024
    ports:
      - "5056:80"
    restart: always
    depends_on:
      - ams_rest
    networks:
      - ams_app2024

  # Database Service (Mysql)
  db:
    image: mysql:latest
    container_name: mce_ams_bd_cont
    volumes:
      - ams_data2024:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: amsfullstack2024
      MYSQL_USER: akram
      MYSQL_PASSWORD: akram@12ere
      MYSQL_ROOT_PASSWORD: root
    networks:
      - ams_app2024

  # PMA Service
  phpmyadmin:
    image: phpmyadmin
    container_name: mce_app_pmadmin_cont
    restart: always
    depends_on:
      - db
    ports:
      - 4046:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - ams_app2024

# Volumes to be created to persist data
volumes:
  ams_data2024:

# Networks to be created to facilitate communication between containers
networks:
  ams_app2024:
